- hosts: tag_name_loadbalancer
  vars:
          - haproxy_port: 8080
          - web_port: 80

  tasks:
          - name: install haproxy
            package:
                    name: haproxy
                    state: present

          - name: configration of haproxy.cfg file
            template:
                    src: "haproxy.cfg"
                    dest: "/etc/haproxy/haproxy.cfg"
            notify:
                    - Restart haproxy

          - name: Starting haproxy service
            service:
                    name: haproxy
                    state: started

  handlers:
          - name: Restart haproxy
            service:
                    name: haproxy
                    state: restarted



- hosts: tag_name_web_server
  vars:
          web_port: 80
  tasks:
          - name: installing httpd software
            package:
                    name: httpd
                    state: present

          - name: installing php software
            package:
                    name: php
                    state: present
          - name: copying content of web server
            copy:
                    content: '<pre>
                              <?php
                              print`/usr/sbin/ifconfig eth0`;
                              ?>
                              </pre>/'
                    dest: /var/www/html/index.php
            notify:
                    - Restart httpd
          
          - name: Starting httpd service
            service:
                    name: httpd
                    state: started

  handlers:
          - name: Restart httpd
            service:
                    name: httpd
                    state: restarted


